definitions:
  bot.BotRequest:
    properties:
      botLink:
        type: string
      name:
        type: string
      platform:
        type: string
      token:
        type: string
    required:
    - name
    - platform
    type: object
  bot.BotResponse:
    properties:
      _id:
        type: string
      botLink:
        type: string
      creator:
        type: string
      name:
        type: string
      platform:
        type: string
      token:
        type: string
    required:
    - name
    - platform
    type: object
  bot.BotStructArrayResponse:
    properties:
      bots:
        items:
          $ref: '#/definitions/bot.BotResponse'
        type: array
    type: object
  bot.BotStructResponse:
    properties:
      bot:
        $ref: '#/definitions/bot.BotResponse'
    type: object
  bot.BotUpdateRequest:
    properties:
      name:
        type: string
      platform:
        type: string
      token:
        type: string
    type: object
  bot.ErrorResponse:
    properties:
      error:
        type: string
      reason:
        type: string
    type: object
  user.MessageResponse:
    properties:
      message:
        example: pong
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/user/ping:
    get:
      consumes:
      - application/json
      description: Returns a "pong" message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.MessageResponse'
      security:
      - Bearer: []
      summary: Ping
      tags:
      - user
  /api/bot/:
    post:
      consumes:
      - application/json
      description: Create a new bot with the provided information
      parameters:
      - description: Bot request body
        in: body
        name: botRequest
        required: true
        schema:
          $ref: '#/definitions/bot.BotRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Bot created successfully
          schema:
            $ref: '#/definitions/bot.BotStructResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/bot.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/bot.ErrorResponse'
      security:
      - Bearer: []
      summary: Create a new bot
      tags:
      - Bot
  /api/bot/{id}:
    put:
      consumes:
      - application/json
      description: Update an existing bot with the provided information
      parameters:
      - description: Bot ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: Bot request body
        in: body
        name: botRequest
        required: true
        schema:
          $ref: '#/definitions/bot.BotUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Bot updated successfully
          schema:
            $ref: '#/definitions/bot.BotStructResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/bot.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/bot.ErrorResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/bot.ErrorResponse'
      security:
      - Bearer: []
      summary: Update an existing bot
      tags:
      - Bot
  /bot:
    get:
      description: Retrieves a list of all bots for user
      produces:
      - application/json
      responses:
        "200":
          description: List of bots retrieved successfully
          schema:
            $ref: '#/definitions/bot.BotStructArrayResponse'
        "400":
          description: Error getting bots
          schema:
            $ref: '#/definitions/bot.ErrorResponse'
      security:
      - Bearer: []
      summary: Get a list of all bots
      tags:
      - Bot
  /tapi/example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
